# Generated by Django 3.1.4 on 2020-12-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns_app', '0002_auto_20201218_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='good',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='boardmodel',
            name='read',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='boardmodel',
            name='readtext',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
    ]
